metadata:
  name: train_audio_dataset
  display_name: Train
  version: '2.0'
  format: WAV
  sample_rate: 16000
  duration: 5s
classification:
  category_id: train
  priority: 9
  alert_type: high
  color: '#8B4513'
dataset:
  total_files: 267
  sources:
  - ESC-50
  - augmented
  - expanded
  - generated
  audio_format:
    type: WAV
    channels: 1
    sample_rate: 16000
    bit_depth: 16
realtime_config:
  min_confidence: 0.65
  detection_interval_ms: 500
